[project]
name = "m-pass"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "lxml>=5.3.0",
    "matplotlib>=3.9.4",
    "pandas>=2.2.3",
    "ruff>=0.9.4",
]
